kubectl delete deploy isamruntime
kubectl delete deploy isamwrprp1
kubectl delete deploy isamconfig
kubectl delete deploy openldap
kubectl delete deploy postgresql
kubectl delete deploy isamdsc
kubectl delete service isamconfig
kubectl delete service isamruntime
kubectl delete service isamwrprp1
kubectl delete service openldap
kubectl delete service postgresql
kubectl delete service isamdsc
kubectl delete secret configreader
kubectl delete secret samadmin
kubectl delete secret dockerlogin
kubectl delete secret openldap-keys
kubectl delete secret postgresql-keys
kubectl delete pvc isamconfig
kubectl delete pvc ldaplib
kubectl delete pvc ldapsecauthority
kubectl delete pvc ldapslapd
kubectl delete pvc postgresqldata
